---
abstract: 'automate the PhantomJS browser'
author:
  - 'Max Maischein <corion@cpan.org>'
build_requires:
  File::Basename: '0'
  File::Copy: '0'
  File::Find: '0'
  File::Path: '0'
  File::Temp: '0'
  Test::HTTP::LocalServer: '0'
  Test::More: '0'
  Time::HiRes: '0'
  URI::file: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.34, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: WWW-Mechanize-PhantomJS
no_index:
  directory:
    - t
    - inc
requires:
  Carp: '0'
  HTML::Selector::XPath: '0'
  HTTP::Daemon: '0'
  HTTP::Response: '0'
  IO::Socket::INET: '0'
  LWP::Simple: '0'
  Object::Import: '0'
  Scalar::Util: '0'
  Selenium::Remote::Driver: '0.18'
  WWW::Mechanize::Link: '0'
  perl: '5.006'
resources:
  repository: https://github.com/Corion/www-mechanize-phantomjs.git
version: '0.19'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
x_static_install: 1
